tasks:
  - command: PIPUSER=false pip install poetry
  - command: PIPUSER=false poetry install
  - command: PIPUSER=false pip install pre-commit
  - command: PIPUSER=false pre-commit install
  - command: PIPUSER=false pre-commit install-hooks
